### ISSUE TITLE
Error on composer update command

### ISSUE THREAD

**Issue by alancarlosml** [cristianmarint/MotionGym#10]
Hello,

Thank you for sharing your code.

I am getting the following error:

```
Problem 1
    - Root composer.json requires php ^7.1.3 but your php version (8.0.3) does not satisfy that requirement.
  Problem 2
    - laravel/framework[v5.8.0, ..., 5.8.x-dev] require php ^7.1.3 -> your php version (8.0.3) does not satisfy that requirement.
    - Root composer.json requires laravel/framework 5.8.* -> satisfiable by laravel/framework[v5.8.0, ..., 5.8.x-dev].
```

How can I solve it?

**Comment by JoseCigarro** [comment]
Hello, 

You need to have the PHP 7.1.3 version for this project and your computer is running the 8.0.3 version.

I hope it's helpful.

**Comment by JoseCigarro** [comment]
> Hello,
> 
> Thank you for sharing your code.
> 
> I am getting the following error:
> 
> ```
> Problem 1
>     - Root composer.json requires php ^7.1.3 but your php version (8.0.3) does not satisfy that requirement.
>   Problem 2
>     - laravel/framework[v5.8.0, ..., 5.8.x-dev] require php ^7.1.3 -> your php version (8.0.3) does not satisfy that requirement.
>     - Root composer.json requires laravel/framework 5.8.* -> satisfiable by laravel/framework[v5.8.0, ..., 5.8.x-dev].
> ```
> 
> How can I solve it?

Hello,

You need to have the PHP 7.1.3 version for this project and your computer is running the 8.0.3 version.

I hope it's helpful.
