### ISSUE TITLE
Class VoyagerAuth does not exist (View: /home/vagrant/motion/MotionGym/vendor/tcg/voyager/resources/views/dimmers.blade.php)

### ISSUE THREAD

**Issue by julioalpa** [cristianmarint/MotionGym#9]
After login I receive these error message:

Class VoyagerAuth does not exist (View: /home/vagrant/motion/MotionGym/vendor/tcg/voyager/resources/views/dimmers.blade.php) (View: /home/vagrant/motion/MotionGym/vendor/tcg/voyager/resources/views/dimmers.blade.php)

How can fix it?

BR,

**Comment by ahmedch1** [comment]
Same error, what you have done?

**Comment by cristianmarint** [comment]
Hi guys, I'm currently refactoring this project to fix this and others issues
